##  Execute Shell Commands from Python


### Module 
 
The subprocess module
The subprocess.run function
The subprocess.CompletedProcess class
The subprocess.PIPE object
The bytes type
The subprocess.CalledProcessError class

### Executing Shell Commands With subprocess.run
subprocess.run function which provided us with lot of flexibility to execute shell command

```
  >>> import subprocess
  >>> proc = subprocess.run(['ls', '-l'])
  total 2097152
  drwxr-xr-x. 2 root root         32 May 31 06:45 bin
  -rw-r--r--. 1 root root 2147483648 Jan  7  2015 swap
  >>> proc
  CompletedProcess(args=['ls', '-l'], returncode=0)
>>>

```
proc variable returns CompletedProcess object and this provides us with lot of flexibility and we can use 
returncode attribute on proc variable to ensure that it succeeded and return 0


subprocess.run with stdout variable 

```
  >>> proc = subprocess.run(
  ...      ['ls', '-l'],
  ...      stdout=subprocess.PIPE,
  ...      stderr=subprocess.PIPE,
  ...  )
  >>> proc
  CompletedProcess(args=['ls', '-l'], returncode=0, stdout=b'total 2097152\ndrwxr-xr-x. 2 root root         32 May 31 06:45 bin\n-rw-r--r--. 1 root root 2147483648 Jan  7  2015 swap\n', stderr=b'')
```


###Intentionally Raising Errors

The subprocess.run function will not raise an error by default if you execute something that returns a non-zero exit status. 
Hereâ€™s an example of this:

```
   >>> new_proc = subprocess.run(['cat', 'nofile.txt'])
  cat: nofile.txt: No such file or directory
  >>>
  >>> new_proc
  CompletedProcess(args=['cat', 'nofile.txt'], returncode=1)
  >>>

```
In this situation, we might want to raise an error, and if we pass the check argument to the function,
it will raise a subprocess.CalledProcessError if something goes wrong:

```
  >>> error_proc = subprocess.run(['cat', 'nofile.txt'], check=True)
  cat: nofile.txt: No such file or directory
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.7/subprocess.py", line 487, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cat', 'nofile.txt']' returned non-zero exit status 1.
>>>

```



